import React from 'react';
import './Main.scss';

const Main = () => {
  return (
    <div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>Main
    </div>
  );
};

export default Main;
